### ISSUE TITLE
Link to GEE code examples leads to new empty script

### ISSUE THREAD

**Issue by Tschoun** [IPL-UV/kNDVI#4]
None of the three [links](https://code.earthengine.google.com/?accept_repo=users/ispguv/kNDVI) to demonstration or examples in the GEE lead to an actual script, but rather open a new and empty script. I'm logged in with my personal GEE account and am especially interested in seeing the code for the approaches to estimate sigma.

**Comment by almomar2** [comment]
> None of the three [links](https://code.earthengine.google.com/?accept_repo=users/ispguv/kNDVI) to demonstration or examples in the GEE lead to an actual script, but rather open a new and empty script. I'm logged in with my personal GEE account and am especially interested in seeing the code for the approaches to estimate sigma.

The link grants access to the source code as a reader. Check the "Reader" section in your Scripts list after refreshing them in a few seconds.

**Comment by Tschoun** [comment]
Thank you! I refreshed the code editor several times, but missed the refresh button in the scripts section.
